#!/usr/bin/env python3

# SPDX-FileCopyrightText: The RamenDR authors
# SPDX-License-Identifier: Apache-2.0

from drenv import test

test.start("deploy", __file__)
args = test.parse_args()

test.info("Deploying application")
test.deploy()
test.info("Application running on cluster '%s'", test.lookup_cluster())
