# permissions for end users to edit ApplicationVolumeReplications.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ApplicationVolumeReplication-editor-role
rules:
- apiGroups:
  - ramendr.openshift.io
  resources:
  - ApplicationVolumeReplications
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ramendr.openshift.io
  resources:
  - ApplicationVolumeReplications/status
  verbs:
  - get
