# permissions for end users to view clusterpeers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clusterpeers-viewer-role
rules:
- apiGroups:
  - ramendr.openshift.io
  resources:
  - clusterpeers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ramendr.openshift.io
  resources:
  - clusterpeers/status
  verbs:
  - get
