# permissions for end users to view clusterids.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clusterid-viewer-role
rules:
- apiGroups:
  - ramendr.openshift.io
  resources:
  - clusterids
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ramendr.openshift.io
  resources:
  - clusterids/status
  verbs:
  - get
