# permissions for end users to edit clusterpeers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clusterpeers-editor-role
rules:
- apiGroups:
  - ramendr.openshift.io
  resources:
  - clusterpeers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ramendr.openshift.io
  resources:
  - clusterpeers/status
  verbs:
  - get
