# permissions for end users to edit clusterids.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clusterid-editor-role
rules:
- apiGroups:
  - ramendr.openshift.io
  resources:
  - clusterids
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ramendr.openshift.io
  resources:
  - clusterids/status
  verbs:
  - get
