# permissions for end users to edit drclusterpeers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: drclusterpeers-editor-role
rules:
- apiGroups:
  - ramendr.openshift.io
  resources:
  - drclusterpeers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ramendr.openshift.io
  resources:
  - drclusterpeers/status
  verbs:
  - get
