# permissions for end users to view drclusterpeers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: drclusterpeers-viewer-role
rules:
- apiGroups:
  - ramendr.openshift.io
  resources:
  - drclusterpeers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ramendr.openshift.io
  resources:
  - drclusterpeers/status
  verbs:
  - get
