# permissions for end users to view DRPlacementControls.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: drplacementcontrol-viewer-role
rules:
- apiGroups:
  - ramendr.openshift.io
  resources:
  - drplacementcontrols
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ramendr.openshift.io
  resources:
  - drplacementcontrols/status
  verbs:
  - get
