# permissions for end users to edit DRPlacementControls.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: drplacementcontrol-editor-role
rules:
- apiGroups:
  - ramendr.openshift.io
  resources:
  - drplacementcontrols
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ramendr.openshift.io
  resources:
  - drplacementcontrols/status
  verbs:
  - get
