# permissions for end users to edit drpolicy.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: drpolicy-editor-role
rules:
- apiGroups:
  - ramendr.openshift.io
  resources:
  - drpolicy
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ramendr.openshift.io
  resources:
  - drpolicy/status
  verbs:
  - get
