
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ramendr.openshift.io
  resources:
  - volumereplicationgroups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ramendr.openshift.io
  resources:
  - volumereplicationgroups/finalizers
  verbs:
  - update
- apiGroups:
  - ramendr.openshift.io
  resources:
  - volumereplicationgroups/status
  verbs:
  - get
  - patch
  - update
