# permissions for end users to view volumereplicationgroups.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: volumereplicationgroup-viewer-role
rules:
- apiGroups:
  - ramendr.openshift.io
  resources:
  - volumereplicationgroups
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ramendr.openshift.io
  resources:
  - volumereplicationgroups/status
  verbs:
  - get
