# permissions for end users to edit volumereplicationgroups.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: volumereplicationgroup-editor-role
rules:
- apiGroups:
  - ramendr.openshift.io
  resources:
  - volumereplicationgroups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ramendr.openshift.io
  resources:
  - volumereplicationgroups/status
  verbs:
  - get
