apiVersion: ramendr.openshift.io/v1alpha1
kind: VolumeReplicationGroup
metadata:
  name: volumereplicationgroup-sample-1
spec:
  # Add fields here
  affinedCluster: us-central
  applicationName: sample-app
  clusterPeersList:
    - us-northeast
    - us-southwest
  asyncRPOGoalSeconds: 3600
